# Generated by Django 4.2 on 2024-01-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citiesvacancies',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='citiesvacancies',
            name='city',
        ),
        migrations.RemoveField(
            model_name='citiesvacancies',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vacancy',
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Резюме'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='resume_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на резюме'),
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='CitiesVacancies',
        ),
        migrations.DeleteModel(
            name='Vacancies',
        ),
    ]
