# Generated by Django 4.2 on 2024-01-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_alter_citiesvacancies_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume_link',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на резюме'),
        ),
    ]
