# Generated by Django 4.2 on 2024-01-14 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_candidate_resume_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='citizenship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainpage.citizenships', verbose_name='Гражданство'),
        ),
    ]
